/**
 * NYC Cookies - WhatsApp Bot Bootstrap & Autodeploy Script
 * Place this file as 'index.js' at the root of your Bothosting Node.js project.
 * It will automatically clone your GitHub bot repository, pull updates, 
 * configure the .env file, install dependencies, and run your bot with PM2 or node child process.
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// ==================== CONFIGURATION ====================
// Replace this with your actual WhatsApp Bot GitHub repository URL once created!
const GITHUB_REPO_URL = process.env.BOT_GITHUB_REPO || "https://github.com/Team-MCD2/nyc-bot.git";
const APP_DIR_NAME = "nyc-bot-app";
const APP_DIR = path.join(__dirname, APP_DIR_NAME);

// Fallback Environment configuration (will use system env variables if available)
const CONFIG = {
    PORT: process.env.PORT || "3001",
    SITE_API_SECRET: process.env.SITE_API_SECRET || "my-super-secret-nyc-2026",
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL || "https://nyc-cookies-casablanca.vercel.app"
};
// =======================================================

console.log("=== NYC COOKIES BOT DEPLOYMENT MANAGER ===");

// 0. Auto-detect public IP for the user
try {
    const https = require('https');
    https.get('https://api.ipify.org', (res) => {
        let data = '';
        res.on('data', (chunk) => data += chunk);
        res.on('end', () => {
            const ip = data.trim();
            console.log(`\n🌍 ==================================================`);
            console.log(`🌍 VOTRE URL DE BOT POUR VERCEL EST : http://${ip}:${CONFIG.PORT}`);
            console.log(`🌍 ==================================================\n`);
        });
    }).on('error', () => {});
} catch (e) {}

function runCommand(cmd, cwd = __dirname) {
    console.log(`Running: ${cmd}`);
    try {
        execSync(cmd, { cwd, stdio: 'inherit' });
        return true;
    } catch (error) {
        console.error(`Error running command "${cmd}":`, error.message);
        return false;
    }
}

async function bootstrap() {
    // 1. Clone or Pull from GitHub
    if (!fs.existsSync(APP_DIR)) {
        console.log(`\n📂 App directory not found. Cloning repository from ${GITHUB_REPO_URL}...`);
        const cloneSuccess = runCommand(`git clone ${GITHUB_REPO_URL} ${APP_DIR_NAME}`);
        if (!cloneSuccess) {
            console.error("❌ Failed to clone repository. Make sure the repository is public or you have set up SSH keys/GitHub token.");
            process.exit(1);
        }
    } else {
        console.log("\n🔄 App directory exists. Pulling latest changes from GitHub...");
        const pullSuccess = runCommand("git pull", APP_DIR);
        if (!pullSuccess) {
            console.warn("⚠️ Git pull failed. Continuing with existing local files...");
        }
    }

    // 2. Generate the .env file inside the app directory
    console.log("\n⚙️ Generating .env configuration file...");
    const envContent = `# Auto-generated by Bootstrap Script
PORT=${CONFIG.PORT}
SITE_API_SECRET=${CONFIG.SITE_API_SECRET}
NEXT_PUBLIC_SITE_URL=${CONFIG.NEXT_PUBLIC_SITE_URL}
`;
    fs.writeFileSync(path.join(APP_DIR, '.env'), envContent, 'utf8');
    console.log("✅ .env file successfully created/updated.");

    // 3. Install Dependencies inside the app directory
    console.log("\n📦 Installing Node.js dependencies...");
    const installSuccess = runCommand("npm install --omit=dev", APP_DIR);
    if (!installSuccess) {
        console.error("❌ Failed to install dependencies.");
        process.exit(1);
    }
    console.log("✅ Dependencies installed successfully.");

    // 4. Start the Application
    console.log("\n🚀 Starting the WhatsApp Bot...");
    
    // Check if PM2 is available globally or locally
    let usePM2 = false;
    try {
        execSync('pm2 -v', { stdio: 'ignore' });
        usePM2 = true;
    } catch (e) {
        // PM2 not found globally
    }

    if (usePM2) {
        console.log("ℹ️ PM2 detected! Starting application under PM2 manager...");
        
        // Generate PM2 Ecosystem file if not exists
        const pm2ConfigPath = path.join(APP_DIR, 'ecosystem.config.js');
        if (!fs.existsSync(pm2ConfigPath)) {
            const pm2ConfigContent = `module.exports = {
  apps: [
    {
      name: 'nyc-cookies-whatsapp-bot',
      script: './index.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production'
      }
    }
  ]
};`;
            fs.writeFileSync(pm2ConfigPath, pm2ConfigContent, 'utf8');
        }

        // Start/Restart with PM2
        runCommand("pm2 startOrRestart ecosystem.config.js", APP_DIR);
        console.log("✅ Bot is running in the background under PM2! Use 'pm2 status' or 'pm2 logs' to monitor.");
    } else {
        console.log("⚠️ PM2 not found. Starting with direct Node process...");
        console.log("👉 Tip: For production, installing PM2 is highly recommended ('npm install -g pm2').");
        
        // Requiring the bot index.js directly to run within this process
        try {
            const botIndexPath = path.join(APP_DIR, 'index.js');
            // Change working directory so Baileys auth folder and config files are created inside the app directory
            process.chdir(APP_DIR);
            require(botIndexPath);
        } catch (err) {
            console.error("❌ Failed to start the bot process:", err);
            process.exit(1);
        }
    }
}

bootstrap();
